/**
 * The providers and models FuseLLM knows about.
 *
 * OpenRouter ids and prices come from openrouter.ai/api/v1/models (checked
 * 2026-10-09). Listing does not guarantee access under a key's privacy
 * settings or guardrails. Direct ids follow each provider's own naming. Ids drift, so
 * every model's id can be overridden in the Models view, and the provider's
 * /models endpoint can be listed from there to find the current one.
 *
 * `browser` records whether the provider answers a CORS preflight from a web
 * page. Z.ai and NVIDIA do not, which is why GLM and Nemotron only offer the
 * OpenRouter route: a direct key for them could never be used from here.
 */

export type ProviderId =
  | 'openrouter'
  | 'perplexity'
  | 'openai'
  | 'anthropic'
  | 'google'
  | 'deepseek'
  | 'xai'
  | 'moonshot'
  | 'qwen'
  | 'minimax'

export type Wire = 'openai' | 'anthropic' | 'responses'

export interface ProviderDef {
  id: ProviderId
  name: string
  wire: Wire
  baseUrl: string
  keyUrl: string
  keyPrefix?: string
  /** Sends `reasoning_effort` on chat completions. Unknown params 400 on some. */
  effortParam?: 'reasoning_effort' | 'reasoning'
  /** OpenAI reasoning models reject `max_tokens` in favour of this. */
  maxTokensParam?: 'max_tokens' | 'max_completion_tokens'
  note?: string
}

export const PROVIDERS: Record<ProviderId, ProviderDef> = {
  openrouter: {
    id: 'openrouter',
    name: 'OpenRouter',
    wire: 'openai',
    baseUrl: 'https://openrouter.ai/api/v1',
    keyUrl: 'https://openrouter.ai/settings/keys',
    keyPrefix: 'sk-or-',
    effortParam: 'reasoning',
    maxTokensParam: 'max_tokens',
    note: 'One key for the catalog. Model access depends on your OpenRouter privacy settings and guardrails.',
  },
  perplexity: {
    id: 'perplexity',
    name: 'Perplexity',
    wire: 'responses',
    baseUrl: 'https://api.perplexity.ai',
    keyUrl: 'https://www.perplexity.ai/account/api/keys',
    keyPrefix: 'pplx-',
    note: 'Sonar, plus 11 of these models through the Agent API, with live web search built in.',
  },
  openai: {
    id: 'openai',
    name: 'OpenAI',
    wire: 'openai',
    baseUrl: 'https://api.openai.com/v1',
    keyUrl: 'https://platform.openai.com/api-keys',
    keyPrefix: 'sk-',
    effortParam: 'reasoning_effort',
    maxTokensParam: 'max_completion_tokens',
  },
  anthropic: {
    id: 'anthropic',
    name: 'Anthropic',
    wire: 'anthropic',
    baseUrl: 'https://api.anthropic.com/v1',
    keyUrl: 'https://console.anthropic.com/settings/keys',
    keyPrefix: 'sk-ant-',
  },
  google: {
    id: 'google',
    name: 'Google AI Studio',
    wire: 'openai',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    keyUrl: 'https://aistudio.google.com/apikey',
    effortParam: 'reasoning_effort',
    maxTokensParam: 'max_tokens',
  },
  deepseek: {
    id: 'deepseek',
    name: 'DeepSeek',
    wire: 'openai',
    baseUrl: 'https://api.deepseek.com',
    keyUrl: 'https://platform.deepseek.com/api_keys',
    keyPrefix: 'sk-',
    maxTokensParam: 'max_tokens',
  },
  xai: {
    id: 'xai',
    name: 'xAI',
    wire: 'openai',
    baseUrl: 'https://api.x.ai/v1',
    keyUrl: 'https://console.x.ai',
    keyPrefix: 'xai-',
    effortParam: 'reasoning_effort',
    maxTokensParam: 'max_tokens',
  },
  moonshot: {
    id: 'moonshot',
    name: 'Moonshot AI',
    wire: 'openai',
    baseUrl: 'https://api.moonshot.ai/v1',
    keyUrl: 'https://platform.moonshot.ai/console/api-keys',
    keyPrefix: 'sk-',
    maxTokensParam: 'max_tokens',
  },
  qwen: {
    id: 'qwen',
    name: 'Alibaba Cloud (Qwen)',
    wire: 'openai',
    baseUrl: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
    keyUrl: 'https://modelstudio.console.alibabacloud.com',
    keyPrefix: 'sk-',
    maxTokensParam: 'max_tokens',
  },
  minimax: {
    id: 'minimax',
    name: 'MiniMax',
    wire: 'openai',
    baseUrl: 'https://api.minimax.io/v1',
    keyUrl: 'https://www.minimax.io/platform',
    maxTokensParam: 'max_tokens',
  },
}

/** Media-only providers: keys for the Studio and media stages. */
export const MEDIA_PROVIDERS = [
  {
    id: 'elevenlabs' as const,
    name: 'ElevenLabs',
    keyUrl: 'https://elevenlabs.io/app/settings/api-keys',
    keyPrefix: 'sk_',
    note: 'Eleven Music, sound effects and every voice on your account. Restrict the key to those endpoints and set a credit quota.',
  },
  {
    id: 'fal' as const,
    name: 'fal.ai',
    keyUrl: 'https://fal.ai/dashboard/keys',
    note: 'Hundreds of media models: FLUX, Kling, Seedance, lipsync, foley from video, upscaling, background removal.',
  },
]

export const PROVIDER_ORDER: ProviderId[] = [
  'openrouter',
  'perplexity',
  'openai',
  'anthropic',
  'google',
  'deepseek',
  'xai',
  'moonshot',
  'qwen',
  'minimax',
]

/**
 * Collections first (what people shop by), then strengths.
 * top: the frontier picks for hard work. popular: highest token volume on
 * OpenRouter this month. reliable: established providers with steady tool
 * use and uptime. free: free, or has a free tier among its alternates.
 */
export type Tag = 'top' | 'popular' | 'fast' | 'budget' | 'free' | 'reliable' | 'code' | 'research' | 'reasoning' | 'review' | 'writing' | 'web' | 'vision'

export interface ModelDef {
  id: string
  name: string
  short: string
  family: string
  vendor: string
  blurb: string
  openrouter: string
  direct?: { provider: ProviderId; model: string }
  /**
   * Id on Perplexity's Agent API, a third route for a Perplexity key. A
   * `preset:` prefix selects one of its tuned presets instead of a model.
   */
  perplexity?: string
  /** Quick swaps offered next to the id field, e.g. a Pro tier or a free tier. */
  alternates?: { label: string; openrouter: string; direct?: string; perplexity?: string }[]
  /** Searches the web on every answer, with no switch to turn on. */
  webNative?: boolean
  context: number
  maxOutput: number
  /** USD per million tokens, from OpenRouter. Used for the cost estimate. */
  price: { in: number; out: number }
  tags: Tag[]
  /** Accepts a reasoning effort. Where false, "mode" only changes length and tone. */
  effort: boolean
  /** Billed per request by what it runs underneath, so `price` is not a rate (e.g. a router). */
  priceVaries?: boolean
  color: string
}

export const MODELS: ModelDef[] = [
  /* ── Frontier: the models to reach for when the work is hard ───────────── */
  {
    id: 'gpt-astra',
    name: 'GPT-6 Astra',
    short: 'Astra',
    family: 'ChatGPT',
    vendor: 'OpenAI',
    blurb: 'OpenAI flagship. Strongest at hard reasoning, agentic coding and careful review.',
    openrouter: 'openai/gpt-6-astra',
    direct: { provider: 'openai', model: 'gpt-6-astra' },
    alternates: [{ label: 'Astra Pro', openrouter: 'openai/gpt-6-astra-pro', direct: 'gpt-6-astra-pro' }],
    context: 1_050_000,
    maxOutput: 128_000,
    price: { in: 10, out: 50 },
    tags: ['top', 'reliable', 'code', 'reasoning', 'review', 'vision'],
    effort: true,
    color: '#10a37f',
  },
  {
    id: 'gpt-sol',
    name: 'GPT-6.1 Sol',
    short: 'Sol',
    family: 'ChatGPT',
    vendor: 'OpenAI',
    blurb: 'The GPT-6 all-rounder, now 6.1: most of Astra’s quality for planning, writing and everyday code at a fifth of the price.',
    openrouter: 'openai/gpt-6.1-sol',
    // Perplexity's Agent API still lists the 5.6 generation; that route stays on it.
    perplexity: 'openai/gpt-5.6-sol',
    direct: { provider: 'openai', model: 'gpt-6.1-sol' },
    alternates: [
      { label: 'GPT-6.1 Sol Pro', openrouter: 'openai/gpt-6.1-sol-pro', direct: 'gpt-6.1-sol-pro' },
      { label: 'GPT-6 Sol', openrouter: 'openai/gpt-6-sol', direct: 'gpt-6-sol' },
      { label: 'GPT-5.6 Sol', openrouter: 'openai/gpt-5.6-sol', direct: 'gpt-5.6-sol', perplexity: 'openai/gpt-5.6-sol' },
    ],
    context: 1_050_000,
    maxOutput: 128_000,
    price: { in: 2, out: 10 },
    tags: ['top', 'reliable', 'popular', 'writing', 'reasoning', 'code', 'vision'],
    effort: true,
    color: '#10a37f',
  },
  {
    id: 'gpt-terra',
    name: 'GPT-5.6 Terra',
    short: 'Terra',
    family: 'ChatGPT',
    vendor: 'OpenAI',
    blurb: 'Grounded analysis and research synthesis at a mid-tier price.',
    openrouter: 'openai/gpt-5.6-terra',
    perplexity: 'openai/gpt-5.6-terra',
    direct: { provider: 'openai', model: 'gpt-5.6-terra' },
    alternates: [{ label: 'Terra Pro', openrouter: 'openai/gpt-5.6-terra-pro', direct: 'gpt-5.6-terra-pro' }],
    context: 1_050_000,
    maxOutput: 128_000,
    price: { in: 2, out: 12 },
    tags: ['reliable', 'research', 'reasoning', 'vision'],
    effort: true,
    color: '#10a37f',
  },
  {
    id: 'gpt-luna',
    name: 'GPT-6 Luna',
    short: 'Luna',
    family: 'ChatGPT',
    vendor: 'OpenAI',
    blurb: 'Fast, cheap GPT-6 for chat, triage, classification and the bulk steps of a circuit. Among the most used models this month.',
    openrouter: 'openai/gpt-6-luna',
    perplexity: 'openai/gpt-5.6-luna',
    direct: { provider: 'openai', model: 'gpt-6-luna' },
    alternates: [
      { label: 'Luna Pro', openrouter: 'openai/gpt-6-luna-pro', direct: 'gpt-6-luna-pro' },
      { label: 'GPT-5.6 Luna', openrouter: 'openai/gpt-5.6-luna', direct: 'gpt-5.6-luna', perplexity: 'openai/gpt-5.6-luna' },
    ],
    context: 1_050_000,
    maxOutput: 128_000,
    price: { in: 0.1, out: 0.5 },
    tags: ['fast', 'budget', 'popular', 'reliable', 'vision'],
    effort: true,
    color: '#10a37f',
  },
  {
    id: 'claude-fable',
    name: 'Claude Fable 5.1',
    short: 'Fable',
    family: 'Claude',
    vendor: 'Anthropic',
    blurb: "Anthropic's most capable model. Long-horizon coding and the hardest reasoning.",
    openrouter: 'anthropic/claude-fable-5.1',
    perplexity: 'anthropic/claude-fable-5',
    direct: { provider: 'anthropic', model: 'claude-fable-5-1' },
    alternates: [{ label: 'Fable 5', openrouter: 'anthropic/claude-fable-5', direct: 'claude-fable-5', perplexity: 'anthropic/claude-fable-5' }],
    context: 1_000_000,
    maxOutput: 128_000,
    price: { in: 10, out: 50 },
    tags: ['top', 'reliable', 'code', 'reasoning', 'vision'],
    effort: true,
    color: '#d97757',
  },
  {
    id: 'claude-opus',
    name: 'Claude Opus 5.5',
    short: 'Opus',
    family: 'Claude',
    vendor: 'Anthropic',
    blurb: 'Deep reasoning and meticulous review. A natural professor or architect, and cheaper than the Opus 5 it replaces.',
    openrouter: 'anthropic/claude-opus-5.5',
    // Perplexity's Agent API still lists Opus 5; that route stays on it.
    perplexity: 'anthropic/claude-opus-5',
    direct: { provider: 'anthropic', model: 'claude-opus-5-5' },
    alternates: [{ label: 'Opus 5', openrouter: 'anthropic/claude-opus-5', direct: 'claude-opus-5', perplexity: 'anthropic/claude-opus-5' }],
    context: 1_000_000,
    maxOutput: 128_000,
    price: { in: 4, out: 20 },
    tags: ['top', 'reliable', 'reasoning', 'review', 'code', 'writing', 'vision'],
    effort: true,
    color: '#d97757',
  },
  {
    id: 'claude-sonnet',
    name: 'Claude Sonnet 5.5',
    short: 'Sonnet',
    family: 'Claude',
    vendor: 'Anthropic',
    blurb: 'Fast, capable and affordable: the best mix of speed and intelligence for building, editing and technical writing.',
    openrouter: 'anthropic/claude-sonnet-5.5',
    // Perplexity's Agent API still lists Sonnet 5; that route stays on it.
    perplexity: 'anthropic/claude-sonnet-5',
    direct: { provider: 'anthropic', model: 'claude-sonnet-5-5' },
    alternates: [{ label: 'Sonnet 5', openrouter: 'anthropic/claude-sonnet-5', direct: 'claude-sonnet-5', perplexity: 'anthropic/claude-sonnet-5' }],
    context: 1_000_000,
    maxOutput: 128_000,
    price: { in: 2, out: 10 },
    tags: ['reliable', 'popular', 'code', 'writing', 'vision'],
    effort: true,
    color: '#d97757',
  },
  {
    id: 'claude-haiku',
    name: 'Claude Haiku 5.5',
    short: 'Haiku',
    family: 'Claude',
    vendor: 'Anthropic',
    blurb: 'Fast, affordable Claude for routing, extraction and summaries. Base rates apply below 100K input tokens; longer prompts cost more.',
    openrouter: 'anthropic/claude-haiku-5.5',
    direct: { provider: 'anthropic', model: 'claude-haiku-5-5' },
    context: 1_000_000,
    maxOutput: 128_000,
    price: { in: 0.1, out: 0.5 },
    tags: ['fast', 'reliable', 'writing', 'code', 'vision'],
    effort: true,
    color: '#d97757',
  },
  {
    id: 'gemini-pro',
    name: 'Gemini 3.1 Pro',
    short: 'Gemini Pro',
    family: 'Gemini',
    vendor: 'Google',
    blurb: 'Google’s frontier reasoner. Reads text, images, audio, video and PDFs in a million-token window.',
    openrouter: 'google/gemini-3.1-pro-preview',
    direct: { provider: 'google', model: 'gemini-3.1-pro-preview' },
    alternates: [{ label: 'Gemini Pro (always latest)', openrouter: '~google/gemini-pro-latest' }],
    context: 1_048_576,
    maxOutput: 65_536,
    price: { in: 2, out: 12 },
    tags: ['top', 'reliable', 'reasoning', 'research', 'code', 'vision'],
    effort: true,
    color: '#4285f4',
  },
  {
    id: 'gemini-flash',
    name: 'Gemini 3.8 Flash',
    short: 'Gemini',
    family: 'Gemini',
    vendor: 'Google',
    blurb: 'Fast, cheap, a million tokens of context, and it watches video and listens to audio. A tireless research assistant.',
    openrouter: 'google/gemini-3.8-flash',
    perplexity: 'google/gemini-3.8-flash',
    direct: { provider: 'google', model: 'gemini-3.8-flash' },
    alternates: [{ label: 'Gemini 3.5 Flash Lite (cheaper)', openrouter: 'google/gemini-3.5-flash-lite', direct: 'gemini-3.5-flash-lite' }],
    context: 1_048_576,
    maxOutput: 65_536,
    price: { in: 0.75, out: 3.75 },
    tags: ['fast', 'reliable', 'popular', 'research', 'vision'],
    effort: true,
    color: '#4285f4',
  },
  {
    id: 'gemma',
    name: 'Gemma 4 31B',
    short: 'Gemma',
    family: 'Gemini',
    vendor: 'Google',
    blurb: 'Google’s open-weight model that also sees images and video. Free on OpenRouter, a cheap paid tier when you need it private.',
    openrouter: 'google/gemma-4-31b-it:free',
    alternates: [
      { label: 'Free tier', openrouter: 'google/gemma-4-31b-it:free' },
      { label: 'Paid (private)', openrouter: 'google/gemma-4-31b-it' },
      { label: 'Gemma 4 26B A4B (free, faster)', openrouter: 'google/gemma-4-26b-a4b-it:free' },
    ],
    context: 262_144,
    maxOutput: 32_768,
    price: { in: 0, out: 0 },
    tags: ['free', 'writing', 'vision'],
    effort: true,
    color: '#4285f4',
  },
  {
    id: 'kimi-k3',
    name: 'Kimi K3',
    short: 'Kimi',
    family: 'Kimi',
    vendor: 'Moonshot AI',
    blurb: 'Agentic coder with long context and strong tool use. Ember-1 is a Kimi K3 tune that reasons in far fewer tokens.',
    openrouter: 'moonshotai/kimi-k3',
    alternates: [
      { label: 'Kimi K2.7 Code (cheaper)', openrouter: 'moonshotai/kimi-k2.7-code' },
      { label: 'Fireworks Ember-1 (shorter reasoning)', openrouter: 'fireworks/ember-1' },
    ],
    perplexity: 'perplexity/kimi-k3',
    direct: { provider: 'moonshot', model: 'kimi-k3' },
    context: 1_048_576,
    maxOutput: 943_718,
    price: { in: 0.5, out: 12 },
    tags: ['code', 'research', 'reasoning', 'vision'],
    effort: true,
    color: '#7c5cff',
  },
  {
    id: 'deepseek-v4-pro',
    name: 'DeepSeek V4 Pro',
    short: 'DeepSeek',
    family: 'DeepSeek',
    vendor: 'DeepSeek',
    blurb: 'Frontier-level reasoning at a fraction of the price. A sharp critic. This is the August general-availability release.',
    openrouter: 'deepseek/deepseek-v4-pro-0813',
    direct: { provider: 'deepseek', model: 'deepseek-v4-pro' },
    alternates: [{ label: 'V4 Pro (April release)', openrouter: 'deepseek/deepseek-v4-pro' }],
    context: 1_048_576,
    maxOutput: 393_216,
    price: { in: 0.66, out: 1.98 },
    tags: ['reasoning', 'code', 'budget'],
    effort: true,
    color: '#4d6bfe',
  },
  {
    id: 'deepseek-flash',
    name: 'DeepSeek V4.1 Flash',
    short: 'DS Flash',
    family: 'DeepSeek',
    vendor: 'DeepSeek',
    blurb: 'Affordable model for coding and everyday circuit steps, with image input and a million-token context window.',
    openrouter: 'deepseek/deepseek-v4.1-flash',
    alternates: [
      { label: 'V4 Flash', openrouter: 'deepseek/deepseek-v4-flash' },
      { label: 'V4 Flash 0731', openrouter: 'deepseek/deepseek-v4-flash-0731' },
    ],
    context: 1_048_576,
    maxOutput: 943_718,
    price: { in: 0.3, out: 1.2 },
    tags: ['popular', 'fast', 'budget', 'code', 'vision'],
    effort: true,
    color: '#4d6bfe',
  },
  {
    id: 'grok',
    name: 'Grok 4.7',
    short: 'Grok',
    family: 'Grok',
    vendor: 'xAI',
    blurb: 'Direct, contrarian and current. Good debater and fact checker. Grok Build is the fast coding variant.',
    openrouter: 'x-ai/grok-4.7',
    perplexity: 'xai/grok-4.6',
    direct: { provider: 'xai', model: 'grok-4.7' },
    alternates: [
      { label: 'Grok 4.6', openrouter: 'x-ai/grok-4.6', direct: 'grok-4.6', perplexity: 'xai/grok-4.6' },
      { label: 'Grok Build 0.1 (coding)', openrouter: 'x-ai/grok-build-0.1', direct: 'grok-build-0.1' },
    ],
    context: 500_000,
    maxOutput: 450_000,
    price: { in: 2, out: 6 },
    tags: ['research', 'reasoning', 'vision'],
    effort: true,
    color: '#8b8b8b',
  },
  {
    id: 'glm',
    name: 'GLM 5.3',
    short: 'GLM',
    family: 'GLM',
    vendor: 'Z.ai',
    blurb: 'Open-weight coder with parallel tool calls. Prime is the same model served 1.5 to 2 times faster. OpenRouter only from a browser.',
    openrouter: 'z-ai/glm-5.3',
    perplexity: 'perplexity/glm-5.3',
    alternates: [{ label: 'GLM 5.3 Prime (faster)', openrouter: 'z-ai/glm-5.3-prime' }],
    context: 1_048_576,
    maxOutput: 943_718,
    price: { in: 0.04, out: 4.8 },
    tags: ['popular', 'code', 'reasoning'],
    effort: true,
    color: '#3b82f6',
  },
  {
    id: 'glm-flash',
    name: 'GLM 5.3 Flash',
    short: 'GLM Flash',
    family: 'GLM',
    vendor: 'Z.ai',
    blurb: 'The second most-used model on OpenRouter. Cheap, sees images and video, and FlashX runs at up to 200 tokens a second.',
    openrouter: 'z-ai/glm-5.3-flash',
    alternates: [{ label: 'GLM 5.3 FlashX (fastest)', openrouter: 'z-ai/glm-5.3-flashx' }],
    context: 1_048_576,
    maxOutput: 943_717,
    price: { in: 0.15, out: 0.5 },
    tags: ['popular', 'fast', 'budget', 'code', 'vision'],
    effort: true,
    color: '#3b82f6',
  },
  {
    id: 'qwen-max',
    name: 'Qwen 3.8 Max',
    short: 'Qwen Max',
    family: 'Qwen',
    vendor: 'Alibaba',
    blurb: 'Alibaba’s 2.4-trillion-parameter flagship. Strong reasoning and code, reads images and video. Its open weights are served too.',
    openrouter: 'qwen/qwen3.8-max-0902',
    alternates: [
      { label: 'Qwen 3.8 Max Prime (faster)', openrouter: 'qwen/qwen3.8-max-prime' },
      { label: 'Qwen 3.8 2.4T open weights', openrouter: 'qwen/qwen3.8-2.4t-a95b' },
    ],
    context: 1_000_000,
    maxOutput: 131_072,
    price: { in: 2, out: 6 },
    tags: ['reasoning', 'code', 'research', 'vision'],
    effort: true,
    color: '#615ced',
  },
  {
    id: 'qwen-flash',
    name: 'Qwen 3.8 Flash',
    short: 'Qwen',
    family: 'Qwen',
    vendor: 'Alibaba',
    blurb: 'Very cheap and quick. Ideal for summaries, drafts and routing steps. Omni Flash also hears audio and watches video.',
    openrouter: 'qwen/qwen3.8-flash',
    direct: { provider: 'qwen', model: 'qwen3.8-flash' },
    alternates: [
      { label: 'Qwen 3.8 Omni Flash (audio and video)', openrouter: 'qwen/qwen3.8-omni-flash' },
    ],
    context: 1_000_000,
    maxOutput: 131_072,
    price: { in: 0.15, out: 0.47 },
    tags: ['fast', 'budget', 'vision'],
    effort: false,
    color: '#615ced',
  },
  {
    id: 'nemotron',
    name: 'Nemotron 3 Ultra',
    short: 'Nemotron',
    family: 'Nemotron',
    vendor: 'NVIDIA',
    blurb: 'Open reasoning model, and the most-used free model on OpenRouter. Lightning is the small, very fast sibling.',
    openrouter: 'nvidia/nemotron-3-ultra-550b-a55b:free',
    perplexity: 'perplexity/nemotron-3-ultra-550b-a55b',
    alternates: [
      { label: 'Free tier', openrouter: 'nvidia/nemotron-3-ultra-550b-a55b:free' },
      { label: 'Paid (faster, private)', openrouter: 'nvidia/nemotron-3-ultra-550b-a55b' },
      { label: 'Nemotron 3.5 Lightning (free)', openrouter: 'nvidia/nemotron-3.5-lightning:free' },
    ],
    context: 1_000_000,
    maxOutput: 65_536,
    price: { in: 0, out: 0 },
    tags: ['free', 'popular', 'reasoning'],
    effort: true,
    color: '#76b900',
  },
  {
    id: 'minimax-m3',
    name: 'MiniMax M3',
    short: 'MiniMax',
    family: 'MiniMax',
    vendor: 'MiniMax',
    blurb: 'Cheap, long-context agent model that reads images and video. Solid second opinion on a budget.',
    openrouter: 'minimax/minimax-m3',
    direct: { provider: 'minimax', model: 'MiniMax-M3' },
    context: 1_048_576,
    maxOutput: 512_000,
    price: { in: 0.3, out: 1.2 },
    tags: ['budget', 'code', 'vision'],
    effort: false,
    color: '#f23f5d',
  },

  /* ── Web-native research ───────────────────────────────────────────────── */
  {
    id: 'sonar-pro',
    name: 'Perplexity Sonar Pro',
    short: 'Sonar',
    family: 'Perplexity',
    vendor: 'Perplexity',
    blurb: 'Answers from the live web with citations on every claim. The fact-finder of any research circuit.',
    openrouter: 'perplexity/sonar-pro',
    perplexity: 'preset:low',
    alternates: [
      { label: 'Sonar (fast)', openrouter: 'perplexity/sonar', perplexity: 'preset:fast' },
      { label: 'Sonar Reasoning Pro', openrouter: 'perplexity/sonar-reasoning-pro', perplexity: 'preset:medium' },
      { label: 'Sonar Pro Search (agentic)', openrouter: 'perplexity/sonar-pro-search' },
    ],
    context: 200_000,
    maxOutput: 8_000,
    price: { in: 3, out: 15 },
    tags: ['reliable', 'research', 'web'],
    effort: false,
    webNative: true,
    color: '#20808d',
  },
  {
    id: 'sonar-deep-research',
    name: 'Perplexity Sonar Deep Research',
    short: 'Deep Research',
    family: 'Perplexity',
    vendor: 'Perplexity',
    blurb: 'Runs dozens of searches and reads the sources before it writes. Slow, thorough, cited.',
    openrouter: 'perplexity/sonar-deep-research',
    perplexity: 'preset:high',
    context: 128_000,
    maxOutput: 115_200,
    price: { in: 2, out: 8 },
    tags: ['research', 'web', 'reasoning'],
    effort: true,
    webNative: true,
    color: '#20808d',
  },
  {
    id: 'openrouter-fusion',
    name: 'OpenRouter Fusion',
    short: 'Fusion',
    family: 'OpenRouter',
    vendor: 'OpenRouter',
    blurb: 'A panel of models researches your prompt in parallel with web search, then one writes the answer. Priced per request by the models it uses.',
    openrouter: 'openrouter/fusion',
    context: 1_000_000,
    maxOutput: 32_000,
    price: { in: 0, out: 0 },
    priceVaries: true,
    tags: ['research', 'web', 'reasoning'],
    effort: false,
    webNative: true,
    color: '#6467f2',
  },
  {
    id: 'openrouter-auto',
    name: 'OpenRouter Auto',
    short: 'Auto',
    family: 'OpenRouter',
    vendor: 'OpenRouter',
    blurb: 'Picks a strong model for each prompt, so you do not have to. Billed at the rate of whichever model answers.',
    openrouter: 'openrouter/auto',
    alternates: [{ label: 'Auto Router (beta)', openrouter: 'openrouter/auto-beta' }],
    context: 2_000_000,
    maxOutput: 64_000,
    price: { in: 0, out: 0 },
    priceVaries: true,
    tags: ['reliable', 'writing', 'vision'],
    effort: true,
    color: '#6467f2',
  },
  {
    id: 'openrouter-free',
    name: 'Free Models Router',
    short: 'Free router',
    family: 'OpenRouter',
    vendor: 'OpenRouter',
    blurb: 'Sends each request to whichever free model is available. Zero cost, but the model and its quality change from answer to answer.',
    openrouter: 'openrouter/free',
    context: 200_000,
    maxOutput: 32_000,
    price: { in: 0, out: 0 },
    tags: ['free'],
    effort: true,
    color: '#6467f2',
  },

  {
    id: 'jev-router',
    name: 'Jev Router',
    short: 'Jev Router',
    family: 'OpenRouter',
    vendor: 'TypeSafe',
    blurb: 'Jev reads each request and picks the model and reasoning effort for it, balancing quality, speed and cost. Billed at the rate of the model it picks.',
    openrouter: 'typesafe/jev-router',
    context: 1_000_000,
    maxOutput: 64_000,
    price: { in: 0, out: 0 },
    priceVaries: true,
    tags: ['reliable', 'fast', 'writing', 'code', 'vision'],
    effort: false,
    color: '#0f766e',
  },
  {
    id: 'pareto-code',
    name: 'Pareto Code Router',
    short: 'Pareto',
    family: 'OpenRouter',
    vendor: 'OpenRouter',
    blurb: 'Sends each coding request to one of a shortlist of top coding models ranked by Artificial Analysis. Billed at the rate of the model it picks.',
    openrouter: 'openrouter/pareto-code',
    context: 2_000_000,
    maxOutput: 64_000,
    price: { in: 0, out: 0 },
    priceVaries: true,
    tags: ['code'],
    effort: false,
    color: '#6467f2',
  },

  {
    id: 'step-5',
    name: 'Step 5 Preview',
    short: 'Step 5',
    family: 'Step',
    vendor: 'StepFun',
    blurb: 'Reasoning and coding model for agent workflows. Reads images and video in a million-token context window.',
    openrouter: 'stepfun/step-5-preview',
    context: 1_000_000,
    maxOutput: 64_000,
    price: { in: 1, out: 2.7 },
    tags: ['code', 'reasoning', 'vision'],
    effort: true,
    color: '#2675f5',
  },
  {
    id: 'mistral-large',
    name: 'Mistral Large 4',
    short: 'Mistral Large',
    family: 'Mistral',
    vendor: 'Mistral AI',
    blurb: 'Multimodal model for reasoning, coding and tool use, with a million-token context window.',
    openrouter: 'mistralai/mistral-large-4-0',
    context: 1_048_576,
    maxOutput: 262_144,
    price: { in: 0.68, out: 2.09 },
    tags: ['code', 'reasoning', 'vision'],
    effort: true,
    color: '#fa520f',
  },
  {
    id: 'apodex-mini',
    name: 'Apodex 1.1 Mini',
    short: 'Apodex',
    family: 'Apodex',
    vendor: 'Apodex',
    blurb: 'Free text reasoning model for research and forecasting, with tool use and structured output.',
    openrouter: 'apodex/apodex-1.1-mini:free',
    context: 262_144,
    maxOutput: 235_929,
    price: { in: 0, out: 0 },
    tags: ['free', 'research', 'reasoning'],
    effort: false,
    color: '#0d9488',
  },
  {
    id: 'pareto-preview',
    name: 'Pareto 26.10 Preview',
    short: 'Pareto Preview',
    family: 'Pareto',
    vendor: 'Unbiased',
    blurb: 'Preview model for research, coding and agent workflows. Accepts text and images.',
    openrouter: 'unbiased/pareto-26.10-preview',
    context: 1_048_576,
    maxOutput: 131_072,
    price: { in: 0.8, out: 3.2 },
    tags: ['research', 'code', 'vision'],
    effort: false,
    color: '#7c3aed',
  },

  /* ── Specialists, open weights and the cheap workhorses ────────────────── */
  {
    id: 'fugu-ultra',
    name: 'Sakana Fugu Ultra v2',
    short: 'Fugu',
    family: 'Fugu',
    vendor: 'Sakana AI',
    blurb: 'A trained orchestrator that coordinates several models behind one answer. Strong on hard, multi-part problems.',
    openrouter: 'sakana/fugu-ultra-v2',
    alternates: [{ label: 'Fugu Max (cheaper)', openrouter: 'sakana/fugu-max' }],
    context: 1_000_000,
    maxOutput: 128_000,
    price: { in: 5, out: 30 },
    tags: ['reasoning', 'research', 'code', 'vision'],
    effort: true,
    color: '#e0484a',
  },
  {
    id: 'inkling',
    name: 'Inkling',
    short: 'Inkling',
    family: 'Inkling',
    vendor: 'Thinking Machines',
    blurb: 'Open-weight multimodal reasoner that also reads images and audio. Has a free tier.',
    openrouter: 'thinkingmachines/inkling',
    alternates: [
      { label: 'Free tier', openrouter: 'thinkingmachines/inkling:free' },
      { label: 'Inkling Small', openrouter: 'thinkingmachines/inkling-small' },
      { label: 'Inkling Small (free)', openrouter: 'thinkingmachines/inkling-small:free' },
    ],
    context: 524_288,
    maxOutput: 471_859,
    price: { in: 1, out: 4.05 },
    tags: ['free', 'reasoning', 'code', 'vision'],
    effort: true,
    color: '#1f2937',
  },
  {
    id: 'hy4',
    name: 'Hy4 (preview)',
    short: 'Hy4',
    family: 'Hy',
    vendor: 'Tencent',
    blurb: 'Large mixture-of-experts model built for coding agents and heavy tool use. Fourth on OpenRouter by volume.',
    openrouter: 'tencent/hy4-preview',
    alternates: [{ label: 'Hy3 (cheaper)', openrouter: 'tencent/hy3' }],
    context: 1_048_576,
    maxOutput: 64_000,
    price: { in: 0.834, out: 2.501 },
    tags: ['popular', 'code', 'reasoning'],
    effort: true,
    color: '#0052d9',
  },
  {
    id: 'laguna',
    name: 'Laguna S 2.1',
    short: 'Laguna',
    family: 'Laguna',
    vendor: 'Poolside',
    blurb: 'Poolside’s agentic coder, free on OpenRouter. Cohere’s North Mini Code is the other free coder worth trying.',
    openrouter: 'poolside/laguna-s-2.1:free',
    alternates: [
      { label: 'Free tier', openrouter: 'poolside/laguna-s-2.1:free' },
      { label: 'Paid (1M context, private)', openrouter: 'poolside/laguna-s-2.1' },
      { label: 'Laguna XS 2.1 (free, faster)', openrouter: 'poolside/laguna-xs-2.1:free' },
      { label: 'Cohere North Mini Code (free)', openrouter: 'cohere/north-mini-code:free' },
    ],
    context: 262_144,
    maxOutput: 32_768,
    price: { in: 0, out: 0 },
    tags: ['free', 'code'],
    effort: true,
    color: '#14b8a6',
  },
  {
    id: 'longcat',
    name: 'LongCat 2.0',
    short: 'LongCat',
    family: 'LongCat',
    vendor: 'Meituan',
    blurb: 'A 1.6-trillion-parameter open model for repository-wide changes and long agent runs, at a budget price.',
    openrouter: 'meituan/longcat-2.0',
    context: 1_048_756,
    maxOutput: 262_144,
    price: { in: 0.3, out: 1.2 },
    tags: ['budget', 'code', 'reasoning'],
    effort: true,
    color: '#ffc300',
  },
  {
    id: 'solar-pro',
    name: 'Solar Pro 4',
    short: 'Solar',
    family: 'Solar',
    vendor: 'Upstage',
    blurb: 'Cheap, long-context model for documents, office work and long agent runs. Solar Mini 4 costs even less.',
    openrouter: 'upstage/solar-pro4',
    alternates: [{ label: 'Solar Mini 4 (cheapest)', openrouter: 'upstage/solar-mini4' }],
    context: 524_288,
    maxOutput: 131_072,
    price: { in: 0.09, out: 0.36 },
    tags: ['popular', 'budget', 'writing', 'research'],
    effort: true,
    color: '#805ad5',
  },
  {
    id: 'mercury',
    name: 'Mercury 2.5',
    short: 'Mercury',
    family: 'Mercury',
    vendor: 'Inception',
    blurb: 'A diffusion model that writes many tokens at once. Very fast, very cheap reasoning.',
    openrouter: 'inception/mercury-2.5',
    context: 260_000,
    maxOutput: 65_536,
    price: { in: 0.04, out: 0.15 },
    tags: ['fast', 'budget'],
    effort: true,
    color: '#f59e0b',
  },
  {
    id: 'ling-flash',
    name: 'Ling 3.1 Flash',
    short: 'Ling',
    family: 'Ling',
    vendor: 'inclusionAI',
    blurb: 'Free text reasoning model for agent workflows. Ling 3.0 Flash and its vision variant remain available below.',
    openrouter: 'inclusionai/ling-3.1-flash',
    // Keep the previous generation available alongside its specialist variants.
    alternates: [
      { label: 'Ling 3.0 Flash', openrouter: 'inclusionai/ling-3.0-flash' },
      { label: 'Flash VL (sees images and video)', openrouter: 'inclusionai/ling-3.0-flash-vl' },
    ],
    context: 262_144,
    maxOutput: 32_768,
    price: { in: 0, out: 0 },
    tags: ['fast', 'budget', 'free', 'reasoning'],
    effort: false,
    color: '#1677ff',
  },
  {
    id: 'schematron',
    name: 'Schematron V2 Turbo',
    short: 'Schematron',
    family: 'Schematron',
    vendor: 'Inference.net',
    blurb: 'Small model that turns HTML into JSON. Built for extraction, not conversation: describe the JSON schema you want.',
    openrouter: 'inference-net/schematron-v2-turbo',
    alternates: [{ label: 'Schematron V2 Small', openrouter: 'inference-net/schematron-v2-small' }],
    context: 128_000,
    maxOutput: 8_192,
    price: { in: 0.03, out: 0.15 },
    tags: ['fast', 'budget'],
    effort: false,
    color: '#6b7280',
  },
  {
    id: 'mimo-pro',
    name: 'MiMo V2.6 Pro',
    short: 'MiMo',
    family: 'MiMo',
    vendor: 'Xiaomi',
    blurb: 'Reads text, images, video and audio at a budget price, with a million-token window. The Flash variant is one of the most used models on OpenRouter.',
    openrouter: 'xiaomi/mimo-v2.6-pro',
    alternates: [
      { label: 'MiMo V2.6 Flash (cheapest)', openrouter: 'xiaomi/mimo-v2.6-flash' },
      { label: 'MiMo V2.6 Pro UltraSpeed', openrouter: 'xiaomi/mimo-v2.6-pro-ultraspeed' },
    ],
    context: 1_050_000,
    maxOutput: 131_072,
    price: { in: 0.435, out: 0.87 },
    tags: ['popular', 'budget', 'fast', 'reasoning', 'vision'],
    effort: true,
    color: '#ff6900',
  },
  {
    id: 'mistral-medium',
    name: 'Mistral Medium 3.5',
    short: 'Mistral',
    family: 'Mistral',
    vendor: 'Mistral AI',
    blurb: 'The European lab’s workhorse: strong multilingual writing and solid code, with Devstral beside it for agentic coding.',
    openrouter: 'mistralai/mistral-medium-3-5',
    alternates: [
      { label: 'Devstral 2512 (coding)', openrouter: 'mistralai/devstral-2512' },
      { label: 'Mistral Small 2603 (cheap)', openrouter: 'mistralai/mistral-small-2603' },
    ],
    context: 262_144,
    maxOutput: 209_715,
    price: { in: 1.5, out: 7.5 },
    tags: ['writing', 'code', 'reasoning', 'vision'],
    effort: true,
    color: '#fa520f',
  },
  {
    id: 'muse-spark',
    name: 'Muse Spark 1.3',
    short: 'Muse',
    family: 'Muse',
    vendor: 'Meta',
    blurb: 'Meta’s frontier model. Takes text, images, video, audio and files, and writes very long answers. The Contributor tier is very cheap.',
    openrouter: 'meta/muse-spark-1.3',
    alternates: [
      { label: 'Muse Spark 1.3 Contributor (cheap)', openrouter: 'meta/muse-spark-1.3-contributor' },
      { label: 'Muse Glimmer 30B (open weights)', openrouter: 'meta/muse-glimmer-30b' },
    ],
    context: 1_048_576,
    maxOutput: 943_718,
    price: { in: 1.25, out: 4.25 },
    tags: ['popular', 'reasoning', 'writing', 'code', 'vision'],
    effort: true,
    color: '#0668e1',
  },
  {
    id: 'gpt-oss',
    name: 'gpt-oss 120B',
    short: 'gpt-oss',
    family: 'gpt-oss',
    vendor: 'OpenAI',
    blurb: 'OpenAI’s open-weight model. Cheap, fast, served by many providers, and a common default for bulk steps.',
    openrouter: 'openai/gpt-oss-120b',
    alternates: [{ label: 'gpt-oss 20B (cheapest)', openrouter: 'openai/gpt-oss-20b' }],
    context: 131_072,
    maxOutput: 117_964,
    price: { in: 0.037, out: 0.17 },
    tags: ['budget', 'fast', 'code'],
    effort: true,
    color: '#10a37f',
  },
  {
    id: 'nova-lite',
    name: 'Nova 2 Lite',
    short: 'Nova',
    family: 'Nova',
    vendor: 'Amazon',
    blurb: 'Amazon’s cheap multimodal model with a million-token window. Reads documents and video as well as text.',
    openrouter: 'amazon/nova-2-lite-v1',
    alternates: [{ label: 'Nova Premier', openrouter: 'amazon/nova-premier-v1' }],
    context: 1_000_000,
    maxOutput: 65_535,
    price: { in: 0.3, out: 2.5 },
    tags: ['budget', 'fast', 'writing', 'vision'],
    effort: true,
    color: '#ff9900',
  },
  {
    id: 'command-a',
    name: 'Command A+',
    short: 'Command',
    family: 'Command',
    vendor: 'Cohere',
    blurb: 'Cohere’s enterprise agent model: grounded answers with citations, strict tool schemas and structured output, now with reasoning and at a fraction of Command A’s price.',
    openrouter: 'cohere/command-a-plus',
    alternates: [{ label: 'Command A', openrouter: 'cohere/command-a' }],
    context: 192_000,
    maxOutput: 64_000,
    price: { in: 0.3, out: 1.5 },
    tags: ['reliable', 'budget', 'research', 'writing', 'vision'],
    effort: true,
    color: '#39594d',
  },
  {
    id: 'seed-code',
    name: 'Seed 2.0 Code',
    short: 'Seed',
    family: 'Seed',
    vendor: 'ByteDance',
    blurb: 'A coding specialist that also sees images and video, for reading a screenshot of the bug alongside the stack trace.',
    openrouter: 'bytedance-seed/seed-2.0-code',
    alternates: [{ label: 'Seed 2.1 Turbo', openrouter: 'bytedance-seed/seed-2-1-turbo' }],
    context: 262_144,
    maxOutput: 131_072,
    price: { in: 0.5, out: 3 },
    tags: ['code', 'reasoning', 'vision'],
    effort: true,
    color: '#325ab4',
  },
  {
    id: 'aion',
    name: 'Aion 3.5',
    short: 'Aion',
    family: 'Aion',
    vendor: 'AionLabs',
    blurb: 'Several specialised models writing together, tuned for fiction, character voice and long interactive stories.',
    openrouter: 'aion-labs/aion-3.5',
    alternates: [{ label: 'Aion 3.5 Mini (cheaper)', openrouter: 'aion-labs/aion-3.5-mini' }],
    context: 262_144,
    maxOutput: 32_768,
    price: { in: 3, out: 6 },
    tags: ['writing'],
    effort: true,
    color: '#c026d3',
  },
]

/**
 * Models that left the catalog, and what replaces them. Chats, circuits and
 * the default model that still name an old id are moved to the new one.
 */
export const RETIRED_MODELS: Record<string, string> = {
  'nex-pro': 'laguna',
  'space-bunny': 'gemma',
}

export const MODEL_BY_ID: Record<string, ModelDef> = Object.fromEntries(MODELS.map(m => [m.id, m]))

export const FAMILIES = [...new Set(MODELS.map(m => m.family))]

export const TAG_LABELS: Record<Tag, string> = {
  top: 'Top picks',
  popular: 'Most used',
  fast: 'Fastest',
  budget: 'Cheap',
  free: 'Free',
  reliable: 'Reliable',
  code: 'Code',
  research: 'Research',
  reasoning: 'Reasoning',
  review: 'Review',
  writing: 'Writing',
  web: 'Web search',
  vision: 'Sees images',
}

/** Case-insensitive match on every word of a query against a model's name, vendor, ids, blurb and tags. */
export function matchesModel(m: ModelDef, query: string): boolean {
  const hay = [m.name, m.short, m.family, m.vendor, m.blurb, m.openrouter, m.direct?.model, ...m.tags, ...(m.alternates ?? []).map(a => `${a.label} ${a.openrouter}`)].join(' ').toLowerCase()
  return query
    .toLowerCase()
    .split(/\s+/)
    .filter(Boolean)
    .every(w => hay.includes(w))
}

/** Price per million tokens in/out as short text, e.g. `$2/$10`, `free`, `varies`. */
export function priceLabel(m: ModelDef, fmt: (n: number) => string): string {
  if (m.priceVaries) return 'varies'
  return m.price.in + m.price.out === 0 ? 'free' : `${fmt(m.price.in)}/${fmt(m.price.out)}`
}

/**
 * How hard a model works on each answer. The ids of the first three predate
 * the rest and are stored in saved chats and circuits, so they never change.
 *
 * Each mode tunes what the providers let us tune — reasoning effort, the
 * output ceiling, web search and its depth — plus a short working brief in
 * the system prompt. There is no per-user fine-tuning behind them.
 */
export type Mode = 'fast' | 'balanced' | 'deep' | 'search' | 'research' | 'perfect'

export const MODES: { id: Mode; label: string; hint: string; icon: string }[] = [
  { id: 'fast', label: 'Fast', hint: 'Low reasoning effort, short answers', icon: '⚡' },
  { id: 'balanced', label: 'Balanced', hint: 'Medium effort, the default', icon: '◐' },
  { id: 'deep', label: 'Thinking', hint: 'Maximum reasoning effort, slower and pricier', icon: '🧠' },
  { id: 'search', label: 'Search', hint: 'Searches the web first and cites what it found; quick', icon: '🌐' },
  { id: 'research', label: 'Research', hint: 'Plans, searches many sources, cross-checks them and writes a cited report; slow', icon: '🔭' },
  { id: 'perfect', label: 'Perfectionist', hint: 'Highest effort: drafts, checks every requirement, revises, then answers', icon: '💎' },
]

/** Modes that switch web search on by themselves, where the route can search. */
export const MODE_WEB: Record<Mode, boolean> = { fast: false, balanced: false, deep: false, search: true, research: true, perfect: false }

/** Output ceiling per mode before the model's own cap and any budget apply. */
export const MODE_MAX_TOKENS: Record<Mode, number> = {
  fast: 8_000,
  balanced: 32_000,
  deep: 64_000,
  search: 16_000,
  research: 64_000,
  perfect: 64_000,
}
