/** Build Cloudflare static-asset headers from the existing Vercel policy, without duplicating it. */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'

const vercel = JSON.parse(readFileSync('vercel.json', 'utf8'))
const rules = vercel.headers.map(rule => ({
  pattern: new RegExp(`^${rule.source}$`),
  headers: Object.fromEntries(rule.headers.map(({ key, value }) => [key, value])),
}))
const paths = readdirSync('dist', { recursive: true, withFileTypes: true })
  .filter(entry => entry.isFile() && !entry.name.startsWith('_'))
  .map(entry => `${entry.parentPath}/${entry.name}`.replace(/^dist/, ''))
  .sort()

function headersFor(path) {
  return Object.assign({}, ...rules.filter(rule => rule.pattern.test(path)).map(rule => rule.headers))
}

// Cloudflare combines repeated headers with commas instead of overriding them.
// Keep only invariant headers in the wildcard block; emit varying headers
// once per asset so CORP and cache policies remain valid.
const common = headersFor('/__unmatched__')
for (const rule of rules) {
  for (const [key, value] of Object.entries(rule.headers)) {
    if (common[key] !== value) delete common[key]
  }
}
const blocks = [['/*', common]]
for (const path of ['/', '/offline-404', ...paths]) {
  const headers = Object.fromEntries(Object.entries(headersFor(path)).filter(([key]) => !(key in common)))
  if (Object.keys(headers).length) blocks.push([path, headers])
}
// Cloudflare serves oauth.html at /oauth after its automatic HTML redirect.
blocks.push(['/oauth', Object.fromEntries(Object.entries(headersFor('/oauth.html')).filter(([key]) => !(key in common)))])

const output = '# Generated by scripts/cloudflare-headers.mjs from vercel.json. Do not edit.\n\n'
  + blocks.map(([path, headers]) => `${path}\n${Object.entries(headers).map(([key, value]) => `  ${key}: ${value}`).join('\n')}`).join('\n\n') + '\n'
if (blocks.length > 100 || output.split('\n').some(line => line.length > 2000)) {
  throw new Error('Cloudflare Workers _headers exceeds its 100-rule or 2,000-character line limit.')
}
writeFileSync('dist/_headers', output)
console.log(`✓ Cloudflare Workers headers generated (${blocks.length} rules)`)
